services:
  VAR_SERVICE_NAME:
    image: VAR_IMAGE_NAME:1.0
    build:
      context: ./images/mariadb
      args:
        MARIADB_VERSION: ${PODMAN_MARIADB_VERSION}
        MARIADB_USER: "${PODMAN_MARIADB_USER}"
        MARIADB_PASS: "${PODMAN_MARIADB_PASS}"
    container_name: VAR_SERVICE_NAME
    environment:
      TZ: ${PODMAN_TIMEZONE}
    networks:
      - VAR_NETWORK_NAME
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      # persistent named volume
      - VAR_SERVICE_NAME-dbdata:/var/lib/mysql
      # expose mysql configuration to host
      #- ./etc/mysql:/container/etc/mysql:Z
      # expose mysql default configuration to host
      #- ./etc/.defaults/mysql:/container/etc/mysql.defaults:Z